### ISSUE TITLE
Change images displayed on the local view

### ISSUE THREAD

**Issue by arimariza** [Vizzuality/half-earth#103]
[https://www.dropbox.com/sh/m2lcjgrh9w3apyd/AAAZizi5u04Lq5Ps5_wD70mGa?dl=0](url)

[https://zpl.io/VYYLxnk](url)

**Comment by guizar** [comment]
A few additional suggestions

**DISPLAY COMMENTS**
When you click on these small round images, a photo different to the preview pops up.
<img width="629" alt="screen shot 2017-10-20 at 14 11 06" src="https://user-images.githubusercontent.com/7090413/31822490-e340a704-b5a0-11e7-9fd5-65fe46d87db6.png">






**TEXT EDITS**
2.  Delete “/With water comes life”
<img width="629" alt="screen shot 2017-10-20 at 14 11 11" src="https://user-images.githubusercontent.com/7090413/31822500-eb7f58b6-b5a0-11e7-9087-905ed9eb2a83.png">
 



3. Delete “Great care must be taken when travelling in a mokovo as hippos could be hidden beneath the surface.”
<img width="623" alt="screen shot 2017-10-20 at 14 11 16" src="https://user-images.githubusercontent.com/7090413/31822524-f966132a-b5a0-11e7-9da6-fb5a4bc5338b.png">








4. Replace text with: “Great care must be taken by people navigating the Okavango Delta as hippos could be hidden beneath the surface.”
<img width="624" alt="screen shot 2017-10-20 at 14 11 21" src="https://user-images.githubusercontent.com/7090413/31822530-fea4980c-b5a0-11e7-99f1-bc2434ea58ed.png">



**CREDITS**
Not all images have the NG logo (only 2 of them show them currently)

thanks!

**Comment by guizar** [comment]
- map markers ✅  and text corrected ✅ 
- NatGeo logo still not showing up in all of these images, opening a different thread specifically for that
