### ISSUE TITLE
Local view  / Clicking on the icons on the map with left sidebar hidden

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#107]
Clicking on the icons on the map loads up the relevant images fine. However, when you hide the LEFT sidebar, and then click the icons, nothing shows up  unless you show the LEFT sidebar and then relevant image shows up
<img width="881" alt="local-icons-leftbar-hidden" src="https://user-images.githubusercontent.com/7090413/31797931-ce05c19e-b528-11e7-849a-a04b6b2a0131.png">

**Comment by vectorsize** [comment]
/!\ connected to #139

**Comment by guizar** [comment]
works well now, thanks
