### ISSUE TITLE
Issues when hiding/unhiding left side bar

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#109]
Scroll down to the biodiversity section, turn on a layer (e.g. amphibians), hide the sidebar and then show the sidebar again. This takes you back to the top of the sidebar which, in turn, toggles off the biodiversity layer

**Comment by vectorsize** [comment]
tip: look into `display: none` vs un-mounting on hide

**Comment by guizar** [comment]
The original issue is now fixed, but a similar behaviour persists within sections (regional, global). 

If you scroll past the biodiversity layers and activate another layer within each section, when hiding the sidebar it will activate the top biodiversity layers 

**Regional**
![regional-hidesidebar](https://user-images.githubusercontent.com/7090413/32169366-14d857f2-bd68-11e7-82ca-890df6e705f9.gif)

**Global**
![global-hidesidebar](https://user-images.githubusercontent.com/7090413/32169367-14f5659a-bd68-11e7-984c-16c2b7eb359f.gif)
