### ISSUE TITLE
Protected Area tiles

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#114]
`Protected Areas` activators in both regional and global views need to be updated with the tiles provided by MoL

Tile: https://cdn.mol.org/half-earth/tiles/reserve-coverage/existing-network/{z}/{x}/{y}

**Activators**

Regional view:
<img width="894" alt="regional" src="https://user-images.githubusercontent.com/7090413/31799099-25497c1e-b530-11e7-8e87-fb4f387364dd.png">

Global view:
<img width="904" alt="global" src="https://user-images.githubusercontent.com/7090413/31799115-2c24345c-b530-11e7-9857-a0ac59ddb6f1.png">

**Comment by vectorsize** [comment]
Two questions here @guizar : 
1. Are we using the same layer both on global and regional?
2. We agreed that the urls won't change anymore, why do we have new urls here?

**Comment by guizar** [comment]
Hey @vectorsize:
1. yes it's the same for both and 2. I know (and sorry about that!) this new tile was shared a few days ago, I updated the spreadsheet  we're using to track urls and thought you had it under your radar

**Comment by guizar** [comment]
gracias @vectorsize!
