### ISSUE TITLE
Legends for the regional view

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#118]
In the legends shown in the regional view, in both the first section (biodiversity paragraph)
<img width="705" alt="screen shot 2017-10-20 at 09 34 00" src="https://user-images.githubusercontent.com/7090413/31812513-28397492-b57b-11e7-80c3-385caa115e2c.png">

and the human pressures paragraph:
<img width="719" alt="screen shot 2017-10-20 at 09 34 20" src="https://user-images.githubusercontent.com/7090413/31812527-31b7e990-b57b-11e7-8017-4a6881afda3f.png">

Let's add the following scales:

taxa | min (-) | max (+)
-- | -- | --
amphibians | 3 | 25
mammals | 8 | 49
birds | 1 | 38
protea | 1 | 69

The values for `restio` are still missing, but let's include what we have now

**Comment by sorodrigo** [comment]
This is the same task as in #94. Its easier if we group this kind of features together. I'll add the info to 94 and close this
