### ISSUE TITLE
go back button should have hardcoded destionations

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#125]
instead of browser history

**Comment by guizar** [comment]
Almost there - go back button still having issues in the regional section:
https://half-earth.vizzuality.com/regional

**Comment by sorodrigo** [comment]
@guizar Hey! I've seen the reported issue. Is not related to navigation buttons. More to images and birds. Let's close this one and open another.

**Comment by sorodrigo** [comment]
This issue addresses the possibility of navigating back and to an unexpected place when accessing site from a different page than home. 

As of now if you navigate back from:
- global => regional ✅ 
- regional => local ✅ 
- local => home ✅ 

The other issue will be tracked at #141
