### ISSUE TITLE
TEXT EDITS [placeholder]

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#131]
The site text has changed a lot in the past 24 hrs (and is still being reviewed as of now) 
In a couple of hours max I'll pass  `.txt` version of the narrative with tracked changes to  @vectorsize

**Comment by sorodrigo** [comment]
@guizar this is ready to test, just a quick note: Select in global page is still pending to be implemented.

**Comment by guizar** [comment]
looks great!
