### ISSUE TITLE
Issues with the information button (legend pane)

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#139]
When clicking the information button `?` 
- The data sources appear in the same legend window, which makes the text difficult to read
- It is not possible to escape or go back, which freezes the interaction with the page

![data-page](https://user-images.githubusercontent.com/7090413/31850707-063bf82c-b64f-11e7-83ae-02b012693a54.gif)

**Comment by sorodrigo** [comment]
Is this still an issue? can't reproduce @guizar

**Comment by guizar** [comment]
Still showing up in `Safari Version 11.0 (12604.1.38.1.7)`, but in `Firefox 56.0` is working well

**Comment by sorodrigo** [comment]
Wasn't aware this issue was platform specific. Will continue checking.

**Comment by guizar** [comment]
This issue is no longer showing up in Safari `11.0 (12604.1.38.1.7)`
