### ISSUE TITLE
Unexpected crash when navigating from regional to local

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/half-earth#141]
If you land in `/regional` and navigate to `/local` the app crashes. This is due to the map not finding the billboards or something related. I suspect the billboards aren't initialized correctly if you navigate from `/regional` instead of `/intro`

**Comment by guizar** [comment]
Another observation:
- if you land in `/intro` then move to  `/local` then`/regional` and click **back** it takes you back to `local` ✅  
- but from this point, if then try to go to `/regional` again (by clicking the down arrow) the app crashes

**Comment by sorodrigo** [comment]
@guizar We're aware of this issue. It's a `premature paharo situation`, can't really judge the `paharos` until they're ready. Closing
