### ISSUE TITLE
Updates on partner's modal [#70]

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#149]
Edits to partner´s modal #70  suggested  after acceptance tests.
Changes described in [**THIS**](https://docs.google.com/spreadsheets/d/1iWYRqv1PWnGpVc8Ux0yz3NDSyw6FTP2PlXtrlHAyIHw/edit#gid=0) link

**Highlights in yellow:** New logos added to the list
**Highlights in purple:** Icon change (the new url is now listed there)
**Highlights in green:** These logos are currently listed under the `Data Partners` section. They need to be moved to an entirely new section called `Model Conservation Efforts` (which can be listed under the data section)

**Comment by sorodrigo** [comment]
@guizar in the link you provide the name and logo but not the link to the partner's webpage.

**Comment by guizar** [comment]
partner's moda now updated
