### ISSUE TITLE
Incude logo watermarks on local images

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#157]
the images below, shown in `/local`, need to include NatGeo's logo watermark 
<img width="1068" alt="screen shot 2017-10-22 at 09 33 39" src="https://user-images.githubusercontent.com/7090413/31860065-b84d0746-b70c-11e7-901c-34c50b33f3fd.png">
<img width="1053" alt="screen shot 2017-10-22 at 09 33 32" src="https://user-images.githubusercontent.com/7090413/31860066-b8700bf6-b70c-11e7-8581-bde2d40d0b02.png">
<img width="976" alt="screen shot 2017-10-22 at 09 33 23" src="https://user-images.githubusercontent.com/7090413/31860067-b88e1466-b70c-11e7-992e-f9e32a228c49.png">
<img width="1081" alt="screen shot 2017-10-22 at 09 33 11" src="https://user-images.githubusercontent.com/7090413/31860068-b8ac08b8-b70c-11e7-847b-d0a93456d9bc.png">

The logo can be found in this [**link**](https://www.nationalgeographic.org/static/ngs/home/img/logo.e6616dca24df.png), and an example of how to place them is provided below

<img width="294" alt="screen shot 2017-10-22 at 09 41 32" src="https://user-images.githubusercontent.com/7090413/31860125-6c56111a-b70d-11e7-9c6f-63559c9db2e5.png">

**Comment by sorodrigo** [comment]
Where the pictures come with specific authors to credit, let's add it to them.

**Comment by arimariza** [comment]
Logo:
[https://www.dropbox.com/s/auv8468ww9h3ytz/natgeo_white.png?dl=0](url)

Images adapted:
[https://www.dropbox.com/sh/ahg0177tlk18yml/AABW3fJ_hMFZer56YbM8fzNUa?dl=0](url)

Example:
[https://zpl.io/adx6D9l](url)

**Comment by guizar** [comment]
Watermarks added 👍
