### ISSUE TITLE
Further text edits

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#159]
-  Additional text edits are highlighted as suggestions in this [link](https://drive.google.com/open?id=1eJ5rbWbdYaGzKKgtBJzev1jhdtUkxtU9D-QcIc7FhAo)

**Comment by vectorsize** [comment]
we will take a look at this but the separation is due to the fact that paragraphs trigger layers, I think it's possible to remove some of it but keep in mind we have that restriction @guizar
