### ISSUE TITLE
Decide a new red-color and add it to the legend

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#167]
MOL introduced a new red color, we should have a go at it designwhise and include it on the legend.
oing @guizar @arimariza

**Comment by guizar** [comment]
I think we first have to decide if we're using that colour to describe human impacts. @arimariza do you have any recommendations for styling the red bit?
<img width="686" alt="screen shot 2017-10-23 at 14 37 44" src="https://user-images.githubusercontent.com/7090413/31895154-55c5df06-b808-11e7-9152-d5c196ca3722.png">

**Comment by sorodrigo** [comment]
- [ ] Pick a new color and send to MoL
- [ ] Design legend to include the new color.
- [ ] Implement new legend.

**Comment by arimariza** [comment]
<img width="178" alt="screen shot 2017-10-26 at 17 50 40" src="https://user-images.githubusercontent.com/32777310/32062946-445a4656-ba76-11e7-9c44-aac54d509268.png">

**Comment by guizar** [comment]
Tile specification shared with MOL
