### ISSUE TITLE
Add a pop-up to introduce users about the slider on the global view

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#170]
Since the slider feature becomes active once you reached the prioritisation framework section, it needs to be introduced with a popup notification (or similar) informing users about the slider's functionality, and the data they're seeing (e.g. what the grids mean)

![slider-funciton](https://user-images.githubusercontent.com/7090413/31909074-d142f8bc-b830-11e7-8d05-e17c0f45cb46.gif)

**Comment by sorodrigo** [comment]
we said in the meeting we will highlight the change in the UI by flashing the slider background, we still need to think of a way to explain what the slider is doing.

**Comment by guizar** [comment]
Looks good, the earth conserved bar now "blinks" when users reach the prioritisation paragraph. This partly solves the issue, now we need to add information about what the feature is about
