### ISSUE TITLE
Feature requests for navigation

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#171]
Acceptance test request: Add a feature to use the down arrow button to navigate across sections

For example ->  when clicking the down arrow, display the following options:
-  VIEW LOCAL MAP 
- VIEW REGIONAL MAP
-  VIEW GLOBAL MAP

<img width="233" alt="screen shot 2017-10-23 at 20 39 35" src="https://user-images.githubusercontent.com/7090413/31910664-1b12ba22-b836-11e7-82b3-b0150765615e.png">

**Comment by guizar** [comment]
@simaob to discuss this with Sergio

**Comment by arimariza** [comment]
https://zpl.io/bPqN5vD

**Comment by guizar** [comment]
navigation menu looks nice 👍  (and works as expected)
