### ISSUE TITLE
Setup analytic events

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#173]
These are described in the doc below:
https://docs.google.com/document/d/1E_ffg-2HH9_GUG6fAcEHF_KWYl5auNYw7E-rNMYRfJI/edit#

**Comment by craigmmills** [comment]
@Jamie-Gibson can you check for me please.

**Comment by Jamie-Gibson** [comment]
I've updated the original doc to take into account the changes. @sorodrigo or @vectorsize can you take a look at this https://docs.google.com/document/d/1E_ffg-2HH9_GUG6fAcEHF_KWYl5auNYw7E-rNMYRfJI/edit# and let me know if you have any questions before implementing?
