### ISSUE TITLE
Fix vertical spacing in paragraphs

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#178]
- Spacing between paragraphs need to be reduced to make the text more consistent. Please see below:
![out](https://user-images.githubusercontent.com/7090413/31861376-34329c1a-b724-11e7-90b6-a7b190aa6dd3.gif)

**Comment by vectorsize** [comment]
we will take a look at this but the separation is due to the fact that paragraphs trigger layers, I think it's possible to remove some of it but keep in mind we have that restriction @guizar

**Comment by guizar** [comment]
spacing looking good
