### ISSUE TITLE
New "earthometer" controller

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#206]
The dial-type of earthometer slider is back and we won't be using the horizontal slider any longer.

![image](https://user-images.githubusercontent.com/1661889/34110215-4359b5de-e406-11e7-8113-fdc4cbdac7d9.png)

In some cases we will have several values in the same controller, and we'll be switch between them by clicking in the center of the dial, where as other times the center of the dial is only a title for the slider, this has to be taken into account when developing it.

(is that right? in the latest design iteration all of them incorporate the multi-value switch)
/ping @sergioestella @arimariza

**Comment by craigmmills** [comment]
![screen shot 2018-01-11 at 11 37 20](https://user-images.githubusercontent.com/126208/34823836-f5c5e75e-f6c3-11e7-9953-87d287d6f165.png)

Seems to be an issue with the % placement when first going to the earthometer - Firefox 57.0 (okay on chrome, okay on Safari) 

Not a big one this second, but won't close until compatible. 

Also the drag bar should have rounded corners not straight right?
