### ISSUE TITLE
Explore pannel

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#207]
At any given point the user can switch between exploration mode and narrative.

If I understood correctly, the exploration mode will display the same amount of controllers available for the current sections (sometimes that will be only one or two) and allow for a more exploratory experience.

Or do we have all the controllers for the whole page in that tab, available at any point?

/ping @sergioestella @arimariza

**Comment by vectorsize** [comment]
PS:
* The possible interactions in the explore panel must be described in more detail.
I overheard that download won't be an option? how about opacity? are the designs up to date?
* the information displayed when clicking on the info button next to the controls of the explorer panel is not visible in the latest designs.

**Comment by craigmmills** [comment]
@vectorsize I'm assuming this ticket is open until the layers in the explore are all added? I'll close the other as the components seem to be complete, but obviously we'll need some real layers to turn on and off.

**Comment by craigmmills** [comment]
@vectorsize We need to add the prioritisation layer (bubble layer) to the explore section.
