### ISSUE TITLE
Use a basemap closer to the one in the homepage

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#211]
The current basemap is slightly different than the home page's one. The problem here is that the homepage's basemap is not zoomable, just one static image.
What we need to do here is use one existing basemap from a tile provider (i.e. mapbox) and modify the raster images to make it look like the one in the home page (i.e using [mapbox studio](https://www.mapbox.com/studio/) ).

**Comment by craigmmills** [comment]
I can't see this on staging. Still looks like the darker seas version
