### ISSUE TITLE
Text changes and small adjustments

### ISSUE THREAD

**Issue by simaob** [Vizzuality/half-earth#279]
A series of text changes and small adjustments requested:

== Opening ==

- [x] I believe the opening quote should be: “Unless humanity learns a great deal more about global biodiversity and moves quickly to protect it, we will soon lose most of the species composing life on Earth.”
- [x] Recommend delete “Now go” from third paragraph. It will make that sentence parallel in construction with all others in that paragraph. Explore. Discover. Etc
- [x] “Stay-tuned” should not be hyphenated.
- [x] Instead of “follow us”, recommend “join us”. More active participation.
- [x] No comma after “us”
- [x] Not sure if you wanted an ellipsis or a period after “conservation” at the very end. Should be 3 dots or 1, but not 

== Story ==

- [x] Just before the earth-ometer change sentence: "The Half-Earth Project is integrating multiple layers of high-resolution data to identify places where species are insufficiently protected and using this information to guide for conservation." to --> "The Half-Earth Project is integrating multiple layers of high-resolution data to identify places where species are insufficiently protected, and using this information to guide conservation priorities."

== Info Page ==

=== Paragraph under “Biodiversity Richness at 1KM resolution” ===

- [x] comma after “In this region,”
- [x] insert “to” after “used” as in “were used to predict”

=== Paragraph under “Protected Areas” ===

- [x] start  the paragraph with “The WDPA is” to make it a complete sentence.

=== Paragraph under “Key Biodiversity Areas (KBAs)” ===

- [ ] Since we’ve already indicated the KBA acronym, we don’t need to repeat it in the paragraph. Start with KBAs, delete Key Biodiversity Areas

=== Paragraph under “Anthropogenic Impacts on Biodiversity” ===

- [x] Start paragraph with “This map layer” to make it a complete sentence.

=== Paragraph under “Road Building” ===

- [ ] “human induced” should be hyphenated “human-induced”

**Comment by simaob** [comment]
We have the go ahead to these changes now.

**Comment by vectorsize** [comment]
Thanks @simaob , regarding the KBAs changes I have the instruction of removing that section alltogether

**Comment by simaob** [comment]
Looks good to me!
