### ISSUE TITLE
Add footer logos and popup

### ISSUE THREAD

**Issue by vectorsize** [Vizzuality/half-earth#55]

**Comment by guizar** [comment]
Add Vizzuaity 's Logo ✌️

**Comment by guizar** [comment]
Last minute changes

In this section:
<img width="500" alt="screen shot 2017-10-20 at 00 56 31" src="https://user-images.githubusercontent.com/7090413/31799362-8df0c3c0-b531-11e7-9fc8-8ff63ac74f74.png">

- Remove NatGeo's logo
- Add E.O. Wilson Biodiversity Foundation  logo (should appear first in line)
https://eowilsonfoundation.org/wp-content/uploads/2013/03/colorlogo-W-WHITE-TEXT.png

**Comment by sorodrigo** [comment]
Let's try to transmit feature changes ASAP not on acceptance tests.

**Comment by arimariza** [comment]
Ok, guys.. so attached: all the logos that should be displayed on  the footer:
[https://www.dropbox.com/sh/qcmlh82m6wu4a01/AAA1Kdyx6l4_P4_j_01q5U2Xa?dl=0](url)

example of the design on Zeplin:
[https://zpl.io/bL468wd](url)

**Comment by guizar** [comment]
Some minor comments:
- The order of the icons should be as shown in the image below
<img width="349" alt="screen shot 2017-10-21 at 17 58 23" src="https://user-images.githubusercontent.com/7090413/31853951-9af9052e-b689-11e7-8e79-160d0378b35a.png">

- The icon in the middle (no. 1 in the image) is hardly visible
