### ISSUE TITLE
Add links and alt properties to images on partner´s modal.

### ISSUE THREAD

**Issue by hectoruch** [Vizzuality/half-earth#70]

**Comment by guizar** [comment]
Thanks @hectoruch! see some suggestions below:

**Data section**
<img width="1072" alt="data-logos" src="https://user-images.githubusercontent.com/7090413/31790419-4f770970-b50d-11e7-8fb7-5a2241ec20ab.png">

**Research section**
<img width="1131" alt="research-logos" src="https://user-images.githubusercontent.com/7090413/31790421-5197e062-b50d-11e7-9069-b3f449963af4.png">

Please change links to:
1. http://www.amphibians.org/
2. http://www.cambridgeconservation.org/
3. https://www.wcs.org
4. http://www.mcz.harvard.edu
5. http://www.mncn.csic.es
6. https://www.nybg.org
7. http://www.missouribotanicalgarden.org/

**Comment by guizar** [comment]
good to go 👍
