### ISSUE TITLE
Adjust regional zoom level to SA

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#85]
See sample image:
lock it so users can’t manipulate the view (at least in this section). 
https://drive.google.com/open?id=0B_-e2Gtwbvx5VW5hNVVXNFBLQ0U

**Comment by vectorsize** [comment]
glad to hear you find this easy @simaob ! zoom levels are connected to route changes as of today (local/regional/global) and we need to set a new mechanism in place in order to trigger zoom changes based on other arbitrary actions 🙄

**Comment by guizar** [comment]
Almost there: once we're past the regional spider, and reach down to the human pressures paragraph, the zoom level returns to its previous state

<img width="1240" alt="screen shot 2017-10-21 at 19 19 27" src="https://user-images.githubusercontent.com/7090413/31854740-1f755454-b696-11e7-966a-dd4dbe8e3fea.png">
