### ISSUE TITLE
White stork introduction video

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#87]
Introduction video seems out of context

**Comment by arimariza** [comment]
change the video of the landing page, for this one: [https://www.dropbox.com/sh/o9e290kkkpbonp9/AAACZLBoxi0mFvKdXCUH5dQma?dl=0&preview=Aerial-fly-over-view-of-a-herd-of-red-Lechwe-running-through-the-flooded-grasslands-of-the-Okavango-Delta-827142118_4K-4096x2160-%40-29.97p-ProRes-422-(HQ)+(1).mov](url)
