### ISSUE TITLE
Roads building tile

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#90]
Set fill to 'transparent'  -  at small zoom levels it seems to be 'filled' in color black

**Comment by simaob** [comment]
Again providing an example screenshot would be great to better describe the problem, will make it easier to assess how long it takes as well.

**Comment by guizar** [comment]
here it goes: 
in [this](https://half-earth.vizzuality.com/regional) view, in the paragraph below, the `roads building` should not be filled (should be transparent). Source tile is found [here](https://simbiotica.carto.com/dataset/openstreetmaps_southern_africa_roads)

<img width="504" alt="human-pressures-paragraph" src="https://user-images.githubusercontent.com/7090413/31777962-53379686-b4e7-11e7-945c-092583a8fc0d.png">

**Comment by guizar** [comment]
👍  looking good now!
