### ISSUE TITLE
Extinctions line chart

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#92]
Line-chart needs to be better explained: 
- it should contain an X and Y axis to make
- Add full source

**Comment by arimariza** [comment]
Take a look at this:. [http://www.pnas.org/content/114/30/E6089/F4.expansion.html](url)
[https://drive.google.com/file/d/0B8Pd0f4_l05hRVpvM1dxNjY1d1U/view](url)

**Comment by guizar** [comment]
Charts were dropped from the designa
