### ISSUE TITLE
Legends for the global rasters

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#94]
On the legends shown in the global view:
<img width="664" alt="screen shot 2017-10-20 at 09 34 39" src="https://user-images.githubusercontent.com/7090413/31812434-d972aa04-b57a-11e7-811e-242924193b50.png">

Please add the following values to the scale:

taxa | min (-) | max (+)
-- | -- | --
amphibians | 1 | 180
birds | 1 | 1020
cacti | 1 | 93
conifers | 1 | 49
mammals | 1 | 244
turtles | 1 | 22

**Comment by sorodrigo** [comment]
We'll also need it in the regional page:

Let's add the following scales:

taxa | min (-) | max (+)
-- | -- | --
amphibians | 3 | 25
mammals | 8 | 49
birds | 1 | 38
protea | 1 | 69

**Comment by guizar** [comment]
Still missing `protea` legend, but downgrading from the priority list
<img width="531" alt="screen shot 2017-10-21 at 13 04 20" src="https://user-images.githubusercontent.com/7090413/31851570-621e44d6-b660-11e7-9e76-08669c10fe16.png">

**Comment by sorodrigo** [comment]
fixed on staging. Closing
