### ISSUE TITLE
Global biodiversity tiles selector

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#95]
Species layers would work better as selectors (rather than on/off toggle) so that just one appears on the map (amphibians, birds, mammals, conifers, cacti)

**Comment by simaob** [comment]
Do you mean that you'd like them to work as radio buttons? Where you can only select one at a time. Clicking on "Mammals" disables the others?

Is this for this section:

<img width="1280" alt="screen shot 2017-10-19 at 15 24 33" src="https://user-images.githubusercontent.com/10764/31775836-a40ab17a-b4e1-11e7-900c-3686d0161098.png">

**Comment by guizar** [comment]
that's right @simaob

**Comment by vectorsize** [comment]
ping me whoever will implement this since there's no radio, should have been a dropdown type.

**Comment by guizar** [comment]
dropdown menu now in place
