### ISSUE TITLE
Global Spider (Chart 2)

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#96]
- add legend “Percent of species adequately protected”
- make sure it's based on this data source: 
https://docs.google.com/spreadsheets/d/1zBk28eP8H5kt83w2x8bwfJqDkLLPX8z8FG59iKHNYhs/edit#gid=2038236908

**Comment by simaob** [comment]
Probably worth including a screenshot of what chart you are talking about. And if there are designs for the legend or not. If so, please point to them.

**Comment by guizar** [comment]
Sure:
<img width="499" alt="regional-spider" src="https://user-images.githubusercontent.com/7090413/31777429-ede1bf9c-b4e5-11e7-8ee1-c35198e6c117.png">


**Guidelines**
Data points: use variable _percentSpeciesMeetingTargetProtectedAreaViaAny_
Show on hover: use variable _totalSpecies_

**Legends**
totalSpecies: Number of species
percentSpeciesMeetingTargetProtectedAreaViaAny: Percent of species adequately protected

also for reference all is listed in the link above

**Comment by guizar** [comment]
looks great -  just have a minor suggestion (adding the percentage marks would make it more readable) but looks great for now. thanks!
