### ISSUE TITLE
Adjust video on the intro. 

### ISSUE THREAD

**Issue by arimariza** [Vizzuality/half-earth#98]
can it be full screen + header?

**Comment by guizar** [comment]
So full screen + header have been implemented (thanks @hectoruch ), however the video will need to be replaced @arimariza (see Walter's comments). Once we have a new one could you please pass it to Hector?

**Comment by guizar** [comment]
Another feat/issue reported: Add in the ability to skip the intro video (for returning users)

**Comment by hectoruch** [comment]
Thanks to @sorodrigo not to me. He was the one that develops the full screen (video).

**Comment by arimariza** [comment]
Please, change the video of the intro for this one: [https://www.dropbox.com/sh/o9e290kkkpbonp9/AAACZLBoxi0mFvKdXCUH5dQma?dl=0&preview=Aerial-fly-over-view-of-a-herd-of-red-Lechwe-running-through-the-flooded-grasslands-of-the-Okavango-Delta-827142118_4K-4096x2160-%40-29.97p-ProRes-422-(HQ)+(1).mov](url)

**Comment by guizar** [comment]
Just a headsup - there seems to be a code regression in this section, we lost the text saying "Swooping over Botswana’s Okavango Delta, the white stork ..."
